name: Convert Jupyter Notebook to Markdown

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Convert Jupyter notebook to Markdown
      run: |
        jupyter nbconvert --to markdown rapport.ipynb

    - name: Rename to README.md
      run: mv rapport.md README.md

<<<<<<< HEAD
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README.md"
        git push

=======
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}
>>>>>>> 1a86c75f608442a094c4ef99465c0c79d0b42fb2
