name: Jupyter to Markdown

on:
  push:
    paths:
      - '**.ipynb'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert notedown

      - name: Convert Jupyter to Markdown
        run: |
          for notebook in $(find . -name "*.ipynb"); do
            jupyter nbconvert --to markdown $notebook
          done

      - name: Move README
        run: mv README.md README.ipynb.md

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Convert Jupyter notebooks to Markdown" && git push
