name: Convert Jupyter Notebook to Markdown

on:
  push:
    paths:
      - 'rapport.ipynb'
      
      
jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Quarto CLI
        run: npm install -g @quarto-dev/quarto-cli

      - name: Convert Jupyter notebook to Markdown
        run: quarto convert rapport.ipynb --to markdown

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update README.md from rapport.ipynb'
          add: 'README.md'